package It.polimi.ingsw.Message;

public enum MessageContent {
    START, NICKNAME, ASSISTANTCARD, MOVESTUDENT, MOTHERNATURE, CLOUDCHOICE, CARD1, CARD3AND5,  CARD10, CARD12, CHARACTERCARD, SHOWMATCHINFO, PLAYERID, ERROR;
}
